/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddAuthenticatorAppDialog: typeof import('./src/@core/components/AddAuthenticatorAppDialog.vue')['default']
    AppBarSearch: typeof import('./src/@core/components/AppBarSearch.vue')['default']
    AppCardActions: typeof import('./src/@core/components/AppCardActions.vue')['default']
    AppDateTimePicker: typeof import('./src/@core/components/AppDateTimePicker.vue')['default']
    AppDrawerHeaderSection: typeof import('./src/@core/components/AppDrawerHeaderSection.vue')['default']
    AppOtpInput: typeof import('./src/@core/components/AppOtpInput.vue')['default']
    AppPriceInput: typeof import('./src/@core/components/AppPriceInput.vue')['default']
    AppSearchHeader: typeof import('./src/@core/components/AppSearchHeader.vue')['default']
    AppSkeleton: typeof import('./src/@core/components/AppSkeleton.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/CardStatisticsHorizontal.vue')['default']
    CardStatisticsTarget: typeof import('./src/@core/components/CardStatisticsTarget.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    ConfirmDialog: typeof import('./src/@core/components/ConfirmDialog.vue')['default']
    CustomCheckboxes: typeof import('./src/@core/components/CustomCheckboxes.vue')['default']
    CustomCheckboxesWithIcon: typeof import('./src/@core/components/CustomCheckboxesWithIcon.vue')['default']
    CustomCheckboxesWithImage: typeof import('./src/@core/components/CustomCheckboxesWithImage.vue')['default']
    CustomizerSection: typeof import('./src/@core/components/CustomizerSection.vue')['default']
    CustomRadios: typeof import('./src/@core/components/CustomRadios.vue')['default']
    CustomRadiosWithIcon: typeof import('./src/@core/components/CustomRadiosWithIcon.vue')['default']
    CustomRadiosWithImage: typeof import('./src/@core/components/CustomRadiosWithImage.vue')['default']
    DataTableFooter: typeof import('./src/@core/components/DataTableFooter.vue')['default']
    DialogCloseBtn: typeof import('./src/@core/components/DialogCloseBtn.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    I18n: typeof import('./src/@core/components/I18n.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    Notifications: typeof import('./src/@core/components/Notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./src/@core/components/ScrollToTop.vue')['default']
    Shortcuts: typeof import('./src/@core/components/Shortcuts.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
  }
}
