export default [
  {
    heading: 'Analytics',
  },
  {
    title: 'Compare Periods',
    icon: { icon: 'bx-git-compare' },
    to: 'analytics-compare',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Shift Analytics',
    icon: { icon: 'bx-time-five' },
    to: 'shift-analytics',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Cashier Shifts',
    icon: { icon: 'bx-user-check' },
    to: 'analytics-cashier-shifts',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Kitchen Shifts',
    icon: { icon: 'bx-restaurant' },
    to: 'analytics-kitchen-shifts',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Shift Handover',
    icon: { icon: 'bx-transfer-alt' },
    to: 'analytics-shift-handover',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Menu Engineering',
    icon: { icon: 'bx-pie-chart-alt-2' },
    to: 'analytics-menu-engineering',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Demand Forecast',
    icon: { icon: 'bx-bulb' },
    to: 'forecast-tomorrow',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Audit Log',
    icon: { icon: 'bx-history' },
    to: 'audit-log',
    action: 'manage',
    subject: 'all',
  },
]
