export default [
  {
    heading: 'HR',
  },
  {
    title: 'Employees',
    icon: { icon: 'bx-group' },
    to: 'hr-employees',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Departments',
    icon: { icon: 'bx-buildings' },
    to: 'hr-departments',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Salaries',
    icon: { icon: 'bx-money' },
    to: 'hr-salaries',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Expenses',
    icon: { icon: 'bx-receipt' },
    to: 'hr-expenses',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Attendance',
    icon: { icon: 'bx-time' },
    to: 'hr-attendance',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Leaves',
    icon: { icon: 'bx-calendar-event' },
    to: 'hr-leaves',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Contracts',
    icon: { icon: 'bx-file' },
    to: 'hr-contracts',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'HR Cash',
    icon: { icon: 'bx-wallet' },
    to: 'hr-cash',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'HR Documents',
    icon: { icon: 'bx-receipt' },
    to: 'hr-documents',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Events',
    icon: { icon: 'bx-flag' },
    to: 'hr-events',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Expense Categories',
    icon: { icon: 'bx-grid' },
    to: 'hr-expense-categories',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Goals',
    icon: { icon: 'bx-target-lock' },
    to: 'hr-goals',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Leave Balances',
    icon: { icon: 'bx-time' },
    to: 'hr-leave-balances',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Leave Types',
    icon: { icon: 'bx-time' },
    to: 'hr-leave-types',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Reviews',
    icon: { icon: 'bx-star' },
    to: 'hr-reviews',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Shift Templates',
    icon: { icon: 'bx-time-five' },
    to: 'shift-templates',
    action: 'manage',
    subject: 'all',
  },
]
