export default [
  {
    heading: 'Management',
  },
  {
    title: 'Users',
    icon: { icon: 'bx-group' },
    to: 'users',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Categories',
    icon: { icon: 'bx-category' },
    to: 'categories',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Products',
    icon: { icon: 'bx-store' },
    to: 'products',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Orders',
    icon: { icon: 'bx-receipt' },
    to: 'orders',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Places & Tables',
    icon: { icon: 'bx-grid' },
    to: 'places',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Discounts',
    icon: { icon: 'bx-purchase-tag' },
    to: 'discounts',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Shifts',
    icon: { icon: 'bx-time-five' },
    to: 'shifts',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Cash Register',
    icon: { icon: 'bx-wallet' },
    to: 'inkassa',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Loyalty',
    icon: { icon: 'bx-medal' },
    to: 'loyalty',
    action: 'manage',
    subject: 'all',
  },
]
