import { EXPENSE_CATEGORY_PERMISSIONS } from '../access'

export default [
  {
    heading: 'Management',
  },
  {
    title: 'Users',
    icon: { icon: 'bx-group' },
    to: 'users',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Categories',
    icon: { icon: 'bx-category' },
    to: 'categories',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Products',
    icon: { icon: 'bx-store' },
    to: 'products',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Orders',
    icon: { icon: 'bx-receipt' },
    to: 'orders',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Places & Tables',
    icon: { icon: 'bx-grid' },
    to: 'places',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Discounts',
    icon: { icon: 'bx-purchase-tag' },
    to: 'discounts',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'discount_secret_title',
    icon: { icon: 'bx-lock' },
    to: 'discounts-secret-word',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Cashbox Expense Categories',
    icon: { icon: 'bx-folder-open' },
    to: 'cashbox-categories',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Money Control',
    icon: { icon: 'bx-wallet' },
    to: 'money-control',
    action: 'manage',
    subject: 'all',
    anyPermission: ['money.control.view'],
  },
  {
    title: 'Safe & Bank',
    icon: { icon: 'bx-shield' },
    to: 'treasury',
    action: 'manage',
    subject: 'all',
    anyPermission: ['treasury.account.view'],
  },
  {
    title: 'Expense Categories',
    icon: { icon: 'bx-folder-open' },
    to: 'expense-categories',
    action: 'manage',
    subject: 'all',
    anyPermission: EXPENSE_CATEGORY_PERMISSIONS,
  },
  {
    title: 'Loyalty',
    icon: { icon: 'bx-medal' },
    to: 'loyalty',
    action: 'manage',
    subject: 'all',
  },
]
