export default [
  {
    heading: 'Stock',
  },
  {
    title: 'Stock Items',
    icon: { icon: 'bx-package' },
    action: 'manage',
    subject: 'all',
    children: [
      { title: 'Items', to: 'stock-items' },
      { title: 'Stock Levels', to: 'stock-levels' },
      { title: 'Batches', to: 'stock-batches' },
      { title: 'Categories', to: 'stock-categories' },
      { title: 'Units', to: 'stock-units' },
      { title: 'Locations', to: 'stock-locations' },
    ],
  },
  {
    title: 'Suppliers',
    icon: { icon: 'bx-buildings' },
    to: 'stock-suppliers',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Purchase Orders',
    icon: { icon: 'bx-cart' },
    to: 'stock-purchase-orders',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Recipes',
    icon: { icon: 'bx-food-menu' },
    to: 'stock-recipes',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Production Orders',
    icon: { icon: 'bx-cog' },
    to: 'stock-production-orders',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Transfers',
    icon: { icon: 'bx-transfer' },
    to: 'stock-transfers',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Stock Counts',
    icon: { icon: 'bx-list-check' },
    to: 'stock-counts',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Transactions',
    icon: { icon: 'bx-history' },
    to: 'stock-transactions',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Product Links',
    icon: { icon: 'bx-link' },
    to: 'stock-product-links',
    action: 'manage',
    subject: 'all',
  },
  {
    heading: 'Settings',
  },
  {
    title: 'Variance Codes',
    icon: { icon: 'bx-error-circle' },
    to: 'stock-variance-codes',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Stock Settings',
    icon: { icon: 'bx-slider-alt' },
    to: 'stock-settings',
    action: 'manage',
    subject: 'all',
  },
]
