export default [
  {
    heading: 'System',
  },
  {
    title: 'Notifications',
    icon: { icon: 'bx-bell' },
    to: 'notifications',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'App Settings',
    icon: { icon: 'bx-cog' },
    to: 'app-settings',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Roles & Permissions',
    icon: { icon: 'bx-shield-quarter' },
    to: 'settings-roles',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Cashbox Categories',
    icon: { icon: 'bx-folder-open' },
    to: 'cashbox-categories',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Fiscalization',
    icon: { icon: 'bx-receipt' },
    to: 'fiscalization',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'License',
    icon: { icon: 'bx-shield' },
    to: 'licensing-status',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'QR Codes',
    icon: { icon: 'bx-grid' },
    to: 'qr-codes',
    action: 'manage',
    subject: 'all',
  },
  {
    heading: 'Notifications',
  },
  {
    title: 'Notification Queue',
    icon: { icon: 'bx-inbox' },
    to: 'notification-queue',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Notification Settings',
    icon: { icon: 'bx-slider-alt' },
    to: 'notification-settings',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Notification Templates',
    icon: { icon: 'bx-copy' },
    to: 'notification-templates',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Notification Types',
    icon: { icon: 'bx-bell' },
    to: 'notification-types',
    action: 'manage',
    subject: 'all',
  },
]
